pipeline {
    agent any

    stages {
        stage('Preparation') {
            steps {
                checkout scm
                script {
                    commit_id = sh(script: "git rev-parse --short HEAD", returnStdout: true).trim()
                }
            }
        }

        stage('Test') {
            steps {
                nodejs(nodeJSInstallationName: 'nodejs') {
                    sh 'npm install --only=dev'
                    sh 'npm test'
                }
            }
        }

        stage('Docker Build/Push') {
            steps {
                script {
                    docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
                        def app = docker.build("miroadamy/docker-example:${commit_id}", '.')
                        app.push()
                        app.push('latest')
                    }
                }
            }
        }
    }
}
